version: 0.1
environment_variables:
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - npm run build
    post_build:
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
